apiVersion: v1
kind: Template
labels:
  template: custom-jenkins-slave
metadata:
  labels:
    app: jenkins-slave
    template: custom-jenkins-slave
  name: custom-jenkins-slave
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: ${APPLICATION}
    name: ${APPLICATION}
- apiVersion: v1
  metadata:
    name: ${APPLICATION}-build
  kind: BuildConfig
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION}:latest
    runPolicy: Serial
    source:
      git:
        uri: ${SOURCE_REPOSITORY_URL}
        ref: ${SOURCE_REPOSITORY_REF}
      type: Git
      contextDir: ${CONTEXT_DIR}
    strategy:
      type: Docker
      forcePull: true
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: ${SOURCE_IMAGE}     
    triggers: []
parameters:
- description: Base image for application.
  displayName: Base Image
  name: SOURCE_IMAGE
  required: true
- description: Application to build.
  displayName: Application name
  name: APPLICATION
  required: true
- description: Application tag.
  displayName: Application Tag
  name: APPLICATION_TAG
  value: latest_dev
- description: Namespace for Source ImageStream.
  displayName: Namespace
  name: SOURCE_NAMESPACE
  required: true
  value: openshift
  
- description: Namespace for Source ImageStream.
  displayName: Namespace
  name: CONTEXT_DIR
  required: true
  value: ""
- description: Git source URI for application
  displayName: Git Repository URL
  name: SOURCE_REPOSITORY_URL
  required: true
- description: Git branch/tag reference
  displayName: Git Reference
  name: SOURCE_REPOSITORY_REF
